name: Update Version

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'The version bump to apply [possible values: major, minor, patch]'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
      publish:
        description: 'Publish the package to GitHub releases'
        required: false
        type: boolean
        default: true

jobs:
  update-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      VERSION: ${{ steps.update_version.outputs.tag-number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Do a version bump on the package
      - name: Update version by bumping git tag
        id: update_version
        uses: leonsteinhaeuser/git-tag-bump@v1.1.0
        with:
          args: >-
            --bump ${{ github.event.inputs.bump }} --v-prefix --create --actor-name "GitHub Actions" --actor-mail "github-actions[bot]@users.noreply.github.com"

      # Update pyproject.toml with the new version
      - name: Update version in pyproject.toml
        run: |
          VERSION=${{ steps.update_version.outputs.tag-number }}
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" pyproject.toml
          cat pyproject.toml
          
      - name: Commit and push version change
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "Update pyproject.toml version to ${{ steps.update_version.outputs.tag-number }}"
          git push

  build-and-publish:
    runs-on: ubuntu-latest
    needs:
      - update-version
    permissions:
      contents: write
      id-token: write

    if: github.event.inputs.publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.7'

      - name: Set up Python
        run: uv python install

      - name: Build package
        run: uv build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.update-version.outputs.VERSION }}
          release_name: ${{ needs.update-version.outputs.VERSION }}
          draft: false
          prerelease: false
